version: '2'
services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - $PWD/data:/data/db
    ports:
      - "27017:27017"